/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Jedrzej' at '26.10.16 19:57' with Gradle 2.14.1
 *
 * @author Jedrzej, @date 26.10.16 19:57
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
